"""Strategy bounded context package."""

from .asset_analysis_generator import AssetAnalysisGenerator
from .futures_asset_analysis_generator import FuturesAssetAnalysisGenerator
from .strategy import InvalidStrategyError, Strategy
from .value_objects import (
    AssetAnalysis,
    ExplanationReason,
    FuturesAssetAnalysis,
    FuturesMarketObservationContext,
    FuturesRecommendation,
    InvalidAssetAnalysisError,
    InvalidExplanationReasonError,
    InvalidFuturesAssetAnalysisError,
    InvalidFuturesMarketObservationContextError,
    InvalidFuturesRecommendationError,
    InvalidMarketObservationContextError,
    InvalidRecommendationActionError,
    InvalidRecommendationError,
    InvalidRecommendationExplanationError,
    InvalidRecommendationOutcomeError,
    InvalidResearchHorizonError,
    InvalidStrategyIdentityError,
    MarketObservationContext,
    Recommendation,
    RecommendationAction,
    RecommendationExplanation,
    RecommendationOutcome,
    ResearchHorizon,
    StrategyIdentity,
)

__all__ = [
    "AssetAnalysis",
    "InvalidFuturesRecommendationError",
    "InvalidFuturesMarketObservationContextError",
    "InvalidFuturesAssetAnalysisError",
    "FuturesRecommendation",
    "FuturesMarketObservationContext",
    "FuturesAssetAnalysis",
    "FuturesAssetAnalysisGenerator",
    "AssetAnalysisGenerator",
    "ExplanationReason",
    "InvalidAssetAnalysisError",
    "InvalidExplanationReasonError",
    "InvalidMarketObservationContextError",
    "InvalidRecommendationActionError",
    "InvalidRecommendationError",
    "InvalidRecommendationExplanationError",
    "InvalidRecommendationOutcomeError",
    "InvalidResearchHorizonError",
    "InvalidStrategyError",
    "InvalidStrategyIdentityError",
    "MarketObservationContext",
    "Recommendation",
    "RecommendationAction",
    "RecommendationExplanation",
    "RecommendationOutcome",
    "ResearchHorizon",
    "Strategy",
    "StrategyIdentity",
]
